# These are supported funding model platforms

github: # [Viriatto]
patreon: PartyFinder
open_collective: # Replace with a single Open Collective username
ko_fi: partyfinder
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Viriato.PartyFinder
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://tinyurl.com/partyfinderpaypal','https://donatebot.io/checkout/851099370384130099']
